language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "3.10-dev"
  - "pypy"
  - "pypy3"
before_install:
  - pip install -U pip setuptools virtualenvwrapper
  - source virtualenvwrapper.sh
  - wipeenv
install:
  - pip install .
script: python setup.py test
after_success:
  - pip install -U coveralls codecov
  - coveralls
  - codecov
